### PR TITLE
Ignore -Wexpansion-to-defined warning

### LINKED ISSUE #204: Build polluted by __DARWIN_NO_LONG_LONG macro
I have enormously warnings when building Darling:
```
darling/src/libc/include/stdlib.h:172:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
#if !__DARWIN_NO_LONG_LONG
     ^
darling/platform-include/sys/cdefs.h:630:32: note: expanded from macro '__DARWIN_NO_LONG_LONG'
#define __DARWIN_NO_LONG_LONG   (defined(__STRICT_ANSI__) \
                                 ^
In file included from XXX:
darling/src/libc/include/stdlib.h:172:6: warning: macro expansion producing 'defined' has undefined behavior [-Wexpansion-to-defined]
darling/platform-include/sys/cdefs.h:632:9: note: expanded from macro '__DARWIN_NO_LONG_LONG'
                                && !defined(__GNUG__))
```
Build on Arch Linux x86_64:
- Linux 4.4.34 (LTS)
- binutils 2.26.1
- clang 3.9.0
- gcc 6.2.1

I don't see this behavior on TC Build.
Is this warning normal?

### PR DESCRIPTION
**Pull request by X0rg**
Close #204

### CODE REVIEW

**Comment by ahyattdev** [comment]
What `clang` version do you have?

On mine (`3.8.0-2ubuntu4`) whenever something is compiled I get this message:

`warning: unknown warning option '-Wno-expansion-to-defined'; did you mean '-Wno-macro-redefined'? [-Wunknown-warning-option]`

**Comment by X0rg** [comment]
As said in #204, 3.9.
Ok, I'll fix that.

**Comment by ahyattdev** [comment]
It is worth noting that I didn't get the warning mentioned in #204, so conditionally enabling the flag to disable the warning would be best. 

Thanks for looking into this.

**Comment by LubosD** [comment]
I'll revert the change for now, because it's causing some strange failures on the build server.

**Comment by ahyattdev** [comment]
It should be working as of f80d8e3.

**Comment by LubosD** [comment]
Note that now there are some i386 build failures: https://teamcity.dolezel.info/viewLog.html?buildId=1193&buildTypeId=Darling_DebianStableX86

**Comment by ahyattdev** [comment]
I cant imagine valid warning flags varying per architecture. Are you using the same `clang` version for the i386 and x86_64 builds?

```
external/groff/CMakeLists.txt
22:	-Wno-mismatched-new-delete

external/security/OSX/CMakeLists.txt
12:	-Wno-mismatched-new-delete
```

The only projects that use that flag are `groff` and `security`.

**Comment by LubosD** [comment]
Ah, the error is here. Not sure why it appeared now.
https://teamcity.dolezel.info/viewLog.html?buildId=1193&buildTypeId=Darling_DebianStableX86&tab=buildLog#_focus=21030
I'll fix it.

**Pull request merged**
