### PR TITLE
Support module loading from new darling executable

### PR DESCRIPTION
**Pull request by X0rg**
Example:
```
$ getcap /usr/bin/darlingC 
/usr/bin/darlingC = cap_sys_module+ep

$ lsmod | grep mach       
     
$ /usr/bin/darlingC shell
Cannot unshare(CLONE_NEWNS): Operation not permitted

$ lsmod | grep mach
darling_mach           77824  0
```

### CODE REVIEW

**Comment by X0rg** [comment]
About `unloadKernelModule()`, I don't know if we need to unload module when darling exit with non-zero status.
If yes, we should probably add a function/macro to cleanup before exiting, avoiding adding  `unloadKernelModule()` before all `return 1` and `exit(1)`.

**Comment by LubosD** [comment]
I'm against module unloading, there can be many darling processes running. Automatic loading is only a convenience feature.

**Comment by X0rg** [comment]
Ok. Did I need to revert 9e58414? Or can we assume this executable will take options, like `darling unload`?

**Comment by LubosD** [comment]
I'll probably take options, so I'll merge it and just uncomment default unloading.

**Comment by X0rg** [comment]
Ok, thanks. :)

**Pull request merged**
