### PR TITLE
SwiftUI framework stubs

### PR DESCRIPTION
**Pull request by mrolappe**
This adds SwiftUI framework stubs, generated on Catalina.

### CODE REVIEW

**Comment by CuriousTommy** [comment]
I don't think it's a good idea to generate Objective C headers for a Swift library

**Comment by mrolappe** [comment]
You are probably right. What is your suggestion?

**Comment by CuriousTommy** [comment]
TBH... I not sure how we are going to handle the Swift only library. We don't have a build system in place for building Swift source code.

**Comment by CuriousTommy** [comment]
I am going to close this PR. Once the new stub generator supports generating Swift header, you can open a new PR.

**Pull request closed without merging**
