### PR TITLE
MetalPerformanceShaders framework stubs

### PR DESCRIPTION
**Pull request by mrolappe**
This adds MetalPerformanceShaders framework stubs, generated on Catalina.

### CODE REVIEW

**Comment by mrolappe** [comment]
Indeed, oops. It is fixed now.

**Comment by mrolappe** [comment]
@facekapow can this be merged now?

**Comment by facekapow** [comment]
Sorry about that, I'd actually forgotten about these PRs. I'll review them this Sunday, but they should be good to merge.

**Comment by mrolappe** [comment]
no worries. let me know if I can support regarding CI/PRs or otherwise.

**Pull request merged**
