### PR TITLE
limiting recursive file-wiping to known ones created by darling

### PR DESCRIPTION
**Pull request by HinTak**
See #848

### CODE REVIEW

**Comment by bugaevc** [comment]
I'm sorry, but no, we do actually want to wipe `/var/tmp` and `/var/run`, not just those files that launchd/shellspawn create when you start the container — anything any programs you might run would create there.

To fix #848, we need to figure out what has actually gone wrong. If it is indeed these lines that are causing your host files to be wiped, then why.

**Comment by HinTak** [comment]
"/var/run" is on the bottom of the overlay so it does not need to go and likely won't go. I haven't figured out what creates "/var/tmp" itself, but I'd prefer not to touch it if unsure.

**Comment by HinTak** [comment]
I'd beg to differ - it is simply not safe to do recursive delete, regardless of whether that causes #848 .

**Comment by bugaevc** [comment]
I don't think I understand your point — how or why is it not safe to delete recursively?

**Comment by HinTak** [comment]
Also darling's main executable is suid root... I'll really ask you, why should silent and automated recursive delete ever be done? And silently and without asking the user to confirm too?

**Comment by bugaevc** [comment]
Because these are internal temp files that are normally cleaned up on every reboot, so that is what we do / emulate. You're not surprised your host's `/tmp` and `/run` start empty on each reboot, without asking for confirmation, are you? We do the same for container's tmp and run.

**Comment by HinTak** [comment]
And the darling start-up code is a host process - any mistakes, it recurses down host paths...

**Comment by bugaevc** [comment]
FWIW, we do want to not have to run it as setuid root, eventually. But we do check that you own the prefix before doing anything with it, including wiping those directories. If there's a bug there somewhere, we should get *that* fixed.

**Comment by HinTak** [comment]
Well, unfortunately, as I wrote in the bug report, checking ownership does not help - the external drive was mounted by udisks2 on behalf of the console user, and so is the tmpfs used by gnome/dbus ...

**Comment by HinTak** [comment]
I also see in the start up code you try to load the kernel module, which requires root privilege anyway.

**Comment by bugaevc** [comment]
Well, we have no evidence that this wiping logic is actually to blame for clearing your drives; it's only a suspicion of mine. And I don't see any apparent bugs with it that would cause it to ignore `DPREFIX` and operate on the host directory structure.

A step forward would be for you to add some tracing to this code (at least print which directories it's trying to wipe) and try to repro the bug.

**Comment by HinTak** [comment]
Actually I explicitly disabled systemd's unit to periodically wipe /tmp . systemd's defaults to remove any files in /tmp that has not been used within 10 days - I found that crazy.

**Comment by HinTak** [comment]
To be honest I'd prefer not to try to "reproduce" this bug - you think seeing it twice and losing 350 GB in one, and another 20 GB in another, is not enough???

**Comment by HinTak** [comment]
I'd put in every precaution, and every protection I can think of, like this pull, before I even use darling at all again!

**Comment by bugaevc** [comment]
0th rule of Darling development: only ever use Darling on a VM, never on the host (or worse, on your daily driver system).

**Comment by HinTak** [comment]
You should put that in the top level readme - see how many contributors you'd lose.

**Comment by HinTak** [comment]
If I want to run a VM, I'd just run Mac OS X in kvm.

**Comment by bugaevc** [comment]
It's not like we have tons of contributors to lose some... But it is [in the docs](https://docs.darlinghq.org/build-instructions.html): "Be prepared for kernel hangups and crashes, and run Darling on a virtual machine if possible." (And it used to be worded stronger, if memory serves me right.)

Look, I understand you're upset about losing your data — and I can empathize, I've once lost a whole drive too (by accidentally dd'ing to a wrong destination). If you don't want anything like that to happen to you again, don't run software you can't trust to behave without sandboxing it.

If you want to help us track down and fix this bug (if it even is our bug, and not something else on your system), the way to go about that would be to reproduce it (on a VM, of course) and see if it's darling.c wiping wrong directories, or launchd shutting down, or what.

**Comment by HinTak** [comment]
It already happened twice. I'd prefer to see some precautionary code like this pull (not necessarily as is - you are free to improve on it, instead of just closing) to be included, before I even use darling again.

**Comment by HinTak** [comment]
And it is not like that bit in recursive wiping code is carved in stone - even as recent as 6 months ago it was wiping things it should not https://github.com/darlinghq/darling/commit/ff12c564febb12cf9a744cf48c1e35b416b6d836#diff-cd6f834c4e69dc3152d667c814eb15c8

@LubosD so I'd really like this pull to be re-opened, and improved upon if needed, before any further usage.

**Pull request closed without merging**
