### PR TITLE
Update sources

### LINKED ISSUE #856: TARGET_OS_DRIVERKIT missing under Clang 12
I should mention that this is a git build of Clang and of CMake; let me know if you want more precise version information.

**Build Log**
Relevant section (omitted successful targets):
```
[13/15893] Building CXX object src/dyld/CMakeFiles/system_loader.dir/src/dyld2.o
FAILED: src/dyld/CMakeFiles/system_loader.dir/src/dyld2.o 
/usr/bin/ccache /usr/local/bin/clang++  -DDARLING -DDARWIN -DHAVE_STDINT_H=1 -DTARGET_OS_MAC=1 -D_DARWIN_C_SOURCE -D_LIBCPP_NO_EXCEPTIONS=1 -D_LIBC_NO_FEATURE_VERIFICATION -D_POSIX_C_SOURCE -D__APPLE__ -D__DYNAMIC__ -D__MACH__ -I../src/dyld/src -I../src/dyld/dyld3 -I../src/dyld/dyld3/shared-cache -I../src/dyld/include/mach-o -I../src/dyld/include -I../src/external/libcxx/include -Isrc/include -I../src/include -I../src/libc/include -I../src/external/libplatform/include -I../platform-include -I../platform-include/pthread -I../src/libc/derived -I../src/libc/include/NetBSD -I../src/libc/include/FreeBSD -I../src/kernel/libsyscall/wrappers -I../src/kernel/include -I../kernel-include -I../src/duct/include -I../src/libm/include -I../src/simd/include -I../src/CoreAudio/include -I../src/external/SmartCardServices/include -I../src/external/IOKitUser/include -I../src/launchd/liblaunch/include -I../src/sandbox/include -I../src/external/coretls/include -I../src/libmalloc/include -I../src/libinfo/include -I../src/external/syslog/libsystem_asl.tproj/include -I../src/external/openssl/src/include -I../kernel-include/iokit -I../src/external/IOKitUser -I../src/external/openpam/include -I../src/external/sqlite/include -I../src/OpenScripting/include -I../src/libiconv/include -I../src/ncurses/include -I../src/external/corefoundation/include -I../src/external/foundation/include -I../src/external/objc4/runtime/include -I../src/external/corecrypto/include -I../src/external/security/include -I../src/xcselect/include -I../src/libaks/include -I../src/external/icu/include -I../src/external/libpthread/include -I../src/libremovefile/include -I../src/external/libdispatch/include -I../src/external/libclosure/include -I../src/external/cfnetwork/include -I../src/external/cfnetwork/private_include -I../src/external/libxml2/include -Isrc/external/libxml2/include -I../src/external/expat/include -I../src/libedit/include -I../src/external/bzip2/include -I../src/libnotify/include -I../src/opendirectory_internal/include -I../src/external/commoncrypto/include -I../src/quarantine/include -I../src/libpmenergy/include -I../src/copyfile/include -I../src/external/zlib/include -I../src/xar/include -I../src/external/DirectoryService/include -I../src/libresolv/include -I../src/external/cocotron/include -I../src/external/cocotron/AppKit/include -I../src/external/cocotron/CoreText/include -I../src/external/cocotron/QuartzCore/include -I../src/external/cocotron/CoreGraphics/include -I../src/external/cocotron/Onyx2D/include -I../src/external/cocotron/CoreData/include -I../src/external/WTF/include -I../src/external/bmalloc/include -I../src/libsysmon/include -I../src/libcompression/include -I../src/external/dtrace/head -I../src/external/lkm/include -I../src/libDiagnosticMessagesClient/include -I../src/libquit/include -I../src/external/SecurityTokend/include -I../src/external/lzfse/include -I../src/libsandbox/include -I../src/OpenDirectory/include -I../src/frameworks/include -I../src/private-frameworks/include -I../src/lib/include -I../src/launchd/liblaunch -I../src/libc/darwin -I../src/libc/gen -I../src/libc/locale -I../src/libc/locale/FreeBSD -I../src/libc/stdtime/FreeBSD -I../src/kernel/libsyscall/wrappers/libproc -I../src/kernel/emulation/linux/misc -I../src -I../src/sandbox -I../src/external/libclosure -I../src/libutil -I../src/dyld/launch-cache -I../src/dyld -isystem /usr/local/lib/clang/12.0.0/include -Wno-nullability-completeness -Wno-deprecated-declarations -Wno-expansion-to-defined -std=c++17 -Wno-availability -include /home/rdrpenguin/darling/src/duct/include/CrashReporterClient.h   -target x86_64-apple-darwin11 -nostdinc  -DBUILDING_DYLD=1 -gfull -fno-pic -B /home/rdrpenguin/darling/build/src/external/cctools-port/cctools/misc/ -arch i386 -arch x86_64 -MD -MT src/dyld/CMakeFiles/system_loader.dir/src/dyld2.o -MF src/dyld/CMakeFiles/system_loader.dir/src/dyld2.o.d -o src/dyld/CMakeFiles/system_loader.dir/src/dyld2.o -c ../src/dyld/src/dyld2.cpp
clang-12: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
clang-12: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from ../src/dyld/src/dyld2.cpp:98:
In file included from ../src/dyld/src/dyld2.h:31:
../src/dyld/src/ImageLoader.h:46:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
In file included from ../src/dyld/src/dyld2.cpp:98:
In file included from ../src/dyld/src/dyld2.h:31:
In file included from ../src/dyld/src/ImageLoader.h:53:
In file included from ../src/dyld/dyld3/shared-cache/DyldSharedCache.h:41:
In file included from ../src/dyld/dyld3/MachOAnalyzer.h:28:
In file included from ../src/dyld/dyld3/MachOLoaded.h:29:
../src/dyld/dyld3/Array.h:33:6: error: 'TARGET_OS_DRIVERKIT' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if !TARGET_OS_DRIVERKIT && (BUILDING_LIBDYLD || BUILDING_DYLD)
     ^
2 errors generated.
ninja: build stopped: subcommand failed.
```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 12.0.0 |
| CMake | 3.17.3 |
| Linux Kernel | 5.4.0 |
| Darling | fa5348c8a9b338746b91a53a801343a8d046a66d |

### LINKED ISSUE #897: error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone declaration
As noted at #856 I create a new bug report

**Build Log**
What is the build error?
```
In file included from /home/teras/Sources/darling/src/external/libdispatch/src/block.cpp:32:
In file included from /home/teras/Sources/darling/src/external/libdispatch/src/internal.h:1086:
In file included from /home/teras/Sources/darling/src/external/libdispatch/src/object_internal.h:472:
/home/teras/Sources/darling/src/external/objc4/runtime/include/objc/runtime.h:1547:9: error: non-defining declaration of enumeration with a fixed underlying type is only permitted as a standalone declaration; missing list of enumerators? [-Welaborated-enum-base]
typedef OBJC_ENUM(uintptr_t, objc_AssociationPolicy) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/teras/Sources/darling/src/external/objc4/runtime/include/objc/objc-api.h:221:44: note: expanded from macro 'OBJC_ENUM'
#define OBJC_ENUM(_type, _name) enum _name : _type _name; enum _name : _type

                                           ^~~~~~~

```

**System Information**
What system are you building with?

| Software | Version |
| --- | --- |
| Clang | 11.0.0 |
| CMake | 3.19.1 |
| Linux Kernel | 5.9.10-arch1-1 |
| Darling | 1d3b09970856d58d12867f4ee5b9b1bf84cd05c2 |

### PR DESCRIPTION
**Pull request by facekapow**
That's right, it's finally here. It took a while, but I think this branch is finally stable enough to merge!

## Major changes
Well first of all, as the branch name indicates, this is an update to all of our open source Apple code (updated to 10.15.2, but not much changed into 10.15.6). The biggest changes in Apple's code this time are in libpthread (and a few of the other system libraries like libsystem_c and libplatform).

However, this is also a major change for Darling's code as well. Most notably, our kqueue support now happens in-kernel, taking advantage of XNU's kqueue code as well, so our kqueue emulation should be more accurate and easier to maintain now.

Darling's build system also got a slight renovation. Many of our CMake support functions got more features to help support Apple's complex library dependencies and allow us to build them to accurately reflect how they're set up on macOS. I also tried to unify our headers into a single SDK in `/Developer` (though that could still be further organized into a proper SDK).

## Other notable changes
  * Adds LibreSSL (progresses #718; missing BoringSSL)
    * Apple has switched over some OS tools (e.g. curl) to use this instead of SecureTransport, so HTTPS with those should be faster and more stable now (our CoreCrypto implementation still needs much improvement)
  * New `ADDITIONAL_PACKAGES` option for CMake
    * Enables a few non-standard (but very useful) utilities to be built and installed
    * Currently enables:
      * `gnutar` - The GNU version of tar
      * `jsc` - A JavaScript REPL built on JavaScriptCore
      * `ash` - Predecessor to `dash`. Apple plans to replace `/bin/sh` with `ash` , but they haven't done so yet, so this is locked behind `ADDITIONAL_PACKAGES`.
  * Quite a few more stubs and stubbed libraries
    * The biggest of which is libnetwork, which is Apple's shiny new networking library. Most users of this would probably be GUI applications (via the Network framework).
  * Various libsystem_kernel fixes for proper behavior
  * Includes fixes to allow Darling to compile under Clang 11+
    * This fixes #856 and also fixes #897.

## Testing
I've tested much of this branch with as many different programs I could think of. Some have known issues (listed in the next section and for which I will be creating tracking issues), but for the most part, everything is working (at least as well as it is in master).

The mio and tokio testsuites have been a big help in rooting out problems in kqueue, psynch, and libsystem_kernel. Most of the issues found with those have been fixed (with the exceptions being most UDP-related errors).

However, since this is such a big set of changes, I'd like anyone that's willing to go ahead and test it out. Throw anything you can at it, especially stuff that's currently working in master. When you find issues, create an issue and make sure to include the Darling commit you tested it on so we can separate issues with the update from normal issues on master.

## Known issues
I'll create tracking issues for these:
  * `rustup` doesn't work (fails to download anything)
  * `brew install wget` can blow up while trying to install `openssl@1.1`
  * `zsh` doesn't work (hangs forever when trying to run something that's not builtin)
  * `jsc` doesn't work (hangs before going into the REPL)
  * `lldb` crashes semi-randomly (occurs more frequently when trying to attach to a running program)

### CODE REVIEW

**Comment by facekapow** [comment]
For those that want to test out this branch, basically follow the same instructions at https://docs.darlinghq.org/build-instructions.html, except add `--branch=update-source` to the `git clone` command.

**Comment by ahyattdev** [comment]
Awesome @facekapow! I'm trying this out now, just cloned the sources. Trying to build with ninja and got this:

```
vmuser@devubuntu2010:~/darling/build$ ninja
ninja: error: build.ninja:14659: multiple rules generate src/kernel/libsyscall/mach/mach_portXtraceMig.c [-w dupbuild=err]
```

I am not sure if it was introduced by your branch or not. going to continue with making it  warning

**Comment by ahyattdev** [comment]
it fails early on with this:
```
FAILED: src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o 
/usr/bin/clang -DBSDTHREAD_WRAP_LINUX_PTHREAD -DDARLING -DDARWIN -DEMULATED_OSVERSION=\"19G73\" -DEMULATED_RELEASE=\"19.6.0\" -DEMULATED_SYSNAME=\"Darwin\" -DEMULATED_VERSION="\"Darwin Kernel Version 19.6.0\"" -DTARGET_OS_MAC=1 -D_DARWIN_C_SOURCE -D_POSIX_C_SOURCE -D__APPLE__ -D__DYNAMIC__ -D__MACH__ -Isrc/include -I../src/include -I../basic-headers -I../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -IDeveloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I../framework-include -I../src/external/lkm/include -I../src/libDiagnosticMessagesClient/include -I../src/frameworks/include -I../src/private-frameworks/include -I../src/lib/include -I../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2 -IDeveloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2 -I../src/kernel -I../src/kernel/emulation/linux -Isrc/startup -Isrc/kernel/libsyscall -Isrc/kernel/emulation/linux -isystem /usr/lib/llvm-11/lib/clang/11.0.0/include -Wno-nullability-completeness -Wno-deprecated-declarations -Wno-availability -Wno-expansion-to-defined -mmacosx-version-min=10.15 -std=c99 -fvisibility=hidden -fPIC -fno-builtin -ggdb -Wno-int-conversion -Wno-compare-distinct-pointer-types   -target x86_64-apple-darwin19 -ffunction-sections -DVARIANT_DYLD -B /home/vmuser/darling/build/src/external/cctools-port/cctools/misc/ -arch i386 -arch x86_64 -MD -MT src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o -MF src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o.d -o src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o   -c ../src/kernel/emulation/linux/unistd/fchmodat.c
In file included from ../src/kernel/emulation/linux/unistd/fchmodat.c:9:
../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:221:5: error: 'TARGET_OS_EMBEDDED' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_EMBEDDED
    ^
```

**Comment by facekapow** [comment]
> ```
> vmuser@devubuntu2010:~/darling/build$ ninja
> ninja: error: build.ninja:14659: multiple rules generate src/kernel/libsyscall/mach/mach_portXtraceMig.c [-w dupbuild=err]
> ```
> 
> I am not sure if it was introduced by your branch or not. going to continue with making it warning

Hmm, I'll try building with Ninja later and see.

> 
> 
> it fails early on with this:
> 
> ```
> FAILED: src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o 
> /usr/bin/clang -DBSDTHREAD_WRAP_LINUX_PTHREAD -DDARLING -DDARWIN -DEMULATED_OSVERSION=\"19G73\" -DEMULATED_RELEASE=\"19.6.0\" -DEMULATED_SYSNAME=\"Darwin\" -DEMULATED_VERSION="\"Darwin Kernel Version 19.6.0\"" -DTARGET_OS_MAC=1 -D_DARWIN_C_SOURCE -D_POSIX_C_SOURCE -D__APPLE__ -D__DYNAMIC__ -D__MACH__ -Isrc/include -I../src/include -I../basic-headers -I../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -IDeveloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I../framework-include -I../src/external/lkm/include -I../src/libDiagnosticMessagesClient/include -I../src/frameworks/include -I../src/private-frameworks/include -I../src/lib/include -I../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2 -IDeveloper/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2 -I../src/kernel -I../src/kernel/emulation/linux -Isrc/startup -Isrc/kernel/libsyscall -Isrc/kernel/emulation/linux -isystem /usr/lib/llvm-11/lib/clang/11.0.0/include -Wno-nullability-completeness -Wno-deprecated-declarations -Wno-availability -Wno-expansion-to-defined -mmacosx-version-min=10.15 -std=c99 -fvisibility=hidden -fPIC -fno-builtin -ggdb -Wno-int-conversion -Wno-compare-distinct-pointer-types   -target x86_64-apple-darwin19 -ffunction-sections -DVARIANT_DYLD -B /home/vmuser/darling/build/src/external/cctools-port/cctools/misc/ -arch i386 -arch x86_64 -MD -MT src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o -MF src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o.d -o src/kernel/emulation/linux/CMakeFiles/emulation_dyld.dir/unistd/fchmodat.o   -c ../src/kernel/emulation/linux/unistd/fchmodat.c
> In file included from ../src/kernel/emulation/linux/unistd/fchmodat.c:9:
> ../Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:221:5: error: 'TARGET_OS_EMBEDDED' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
> #if TARGET_OS_EMBEDDED
>     ^
> ```
Yeah, @bugaevc told me about this. He had to add some workarounds locally to get it to build. This is actually the same as #856; I've been building with Clang 10 so I wasn't running into it. I'm clean building everything with Clang 12 now and I'll push some fixes for it once I'm done. Currently 50% through the build.

**Comment by ahyattdev** [comment]
@facekapow the VM i just made has clang 11 so that would make sense. OK I will wait until your fixes land since it sounds like you already covered it. It will be great seeing all your work merged in!

**Comment by facekapow** [comment]
Alright, I've pushed some fixes that should allow it to compile with Clang 11+ (tested with Clang 12). This PR should now also fix #856 and #897.

**Comment by ahyattdev** [comment]
@facekapow need to push to file_cmds?

```
fatal: remote error: upload-pack: not our ref 192a2bfdc693f8766acb912b9e11aae4ec1d75a3
Fetched in submodule path 'src/external/file_cmds', but it did not contain 192a2bfdc693f8766acb912b9e11aae4ec1d75a3. Direct fetching of that commit failed.
```

**Comment by bugaevc** [comment]
> `multiple rules generate src/kernel/libsyscall/mach/mach_portXtraceMig.c`

I have a proper fix for that, actually. I'll push it if @facekapow doesn't beat me to it.

**Comment by facekapow** [comment]
> @facekapow need to push to file_cmds?
> 
> ```
> fatal: remote error: upload-pack: not our ref 192a2bfdc693f8766acb912b9e11aae4ec1d75a3
> Fetched in submodule path 'src/external/file_cmds', but it did not contain 192a2bfdc693f8766acb912b9e11aae4ec1d75a3. Direct fetching of that commit failed.
> ```

My bad, yeah, forgot to push `file_cmds` (pushed this fix late last night right before going to bed).

> > `multiple rules generate src/kernel/libsyscall/mach/mach_portXtraceMig.c`
> 
> I have a proper fix for that, actually. I'll push it if @facekapow doesn't beat me to it.

Absolutely, go ahead.

**Comment by ahyattdev** [comment]
cool, darling builds now. just an error on lkm

```
Invoked by kernel build system, building for 5.8.0-31-generic
  MODPOST /home/vmuser/darling/src/external/lkm/Module.symvers
  CC [M]  /home/vmuser/darling/src/external/lkm/darling-mach.mod.o
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
```

**Comment by bugaevc** [comment]
Yep, I was getting the same error yesterday / this morning. It has to do with trying to link the LKM with Clang, but (apparently?) passing flags intended for GCC.

**Comment by facekapow** [comment]
I recently got it building with GCC and I *thought* I had reverted the LKM build system back to using GCC, but I had forgotten the most important part: the CC flag override in the build command. I didn't notice it because I build Darling on my actual machine and install it into a VM, so I was using DKMS to build the LKM.

**Comment by jld3103** [comment]
Cleaned my build dir and started building, but got this:
```log
darling/framework-include/CoreGraphics/CoreGraphicsPrivate.h:4:10: fatal error: 'IOKit/hidsystem/IOLLEvent.h' file not found
```

**Comment by bugaevc** [comment]
That happens if you're missing some recursive submodules

**Comment by jld3103** [comment]
I did `git submodule init` and `git submodule update`

**Comment by demhademha** [comment]
I get the following issue when using ninja: 
Oh I get this error: 
In file included from ../src/external/foundation/src/NSArray.m:10:
In file included from ../src/external/foundation/src/NSCoderInternal.h:2:
In file included from ../framework-include/CoreGraphics/CoreGraphics.h:31:
In file included from ../framework-include/CoreGraphics/CGEvent.h:27:
../framework-include/CoreGraphics/CoreGraphicsPrivate.h:4:10: fatal error: 'IOKit/hidsystem/IOLLEvent.h' file not found
#include <IOKit/hidsystem/IOLLEvent.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[19/19829] Building C object src/libm/CMakeFiles/system_m_static.dir/Source/Intel/complex.o
ninja: build stopped: subcommand failed.
Thanks for the support.

**Comment by facekapow** [comment]
@demhademha Did you do `git submodule update --init -recursive` when switching to the `update-sources` branch? Or did you do a fresh clone?

**Comment by demhademha** [comment]
First I cloned the master branch, 
git clone --recursive https://github.com/darlinghq/darling 
git checkout update-sources 
git submodule update --recursive 
git submodule init

**Comment by theslimshaney** [comment]
@demhademha try it as suggested: `git submodule update --init -recursive`
You probably don't have [IOHIDFamily](https://github.com/darlinghq/darling-IOHIDFamily) submodule, [which is a submodule of IOKitUser](https://github.com/darlinghq/darling-iokituser/blob/update-sources/.gitmodules)
Or from `src/darling/src/external/IOKitUser` you can load the submodules and there you should see `IOHIDFamily/IOHIDSystem/IOKit/hidsystem/IOLLEvent.h` as a text file.

**Comment by ahyattdev** [comment]
@facekapow does https://github.com/darlinghq/darling/pull/898/commits/c8c8fbaa721c9bd97a630fa4270a607a89ba3cde mean that 64 bit only builds now work?

**Comment by facekapow** [comment]
Yep.

**Comment by johnothwolo** [comment]
> * Adds LibreSSL (progresses [Compile BoringSSL and LibreSSL #718](https://github.com/darlinghq/darling/issues/718); missing BoringSSL

@facekapow maybe change to below (to close issue)?

* Adds LibreSSL (resolves [Compile BoringSSL and LibreSSL #718](https://github.com/darlinghq/darling/issues/718); missing BoringSSL

**Comment by facekapow** [comment]
@johnothwolo Well, this PR has already been merged (2 years ago!). Besides, it doesn't actually resolve that issue; we're still missing BoringSSL.

**Pull request merged**
