### PR TITLE
Update Submodules

### PR DESCRIPTION
**Pull request by Fancy2209**

### CODE REVIEW

**Comment by Fancy2209** [comment]
oh I messed up libressl

**Comment by Fancy2209** [comment]
Weird, I set the right branch but it seems it still pulled master?

**Comment by CuriousTommy** [comment]
Why are you updating the `libressl` submodules? It looks like they already have the latest changes.

**Comment by Fancy2209** [comment]
I ran the git command to update submodules and it messed with libressl,
I'll try to manually update everything but it

CuriousTommy ***@***.***> escreveu no dia segunda, 15/01/2024
à(s) 02:56:

**Comment by CuriousTommy** [comment]
So it looks likes for both [darling-openjdk](https://github.com/darlinghq/darling-openjdk) and [darling-SmartCardServices](https://github.com/darlinghq/darling-SmartCardServices), I forgot to merge my `remove_lkm` changes into the default branch, oops...

**Comment by CuriousTommy** [comment]
> I ran the git command to update submodules and it messed with libressl,

I recommend reading [7.11 Git Tools - Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) if you are new to submodules.

Think of `.gitmodules` as information on where we need to clone the repo from. However, it does not have information on what commit we need to checkout from the submodule.

What you need to is `cd` into the submodule and checkout the commit you want to use. When you get back to the `darling` repo and run `git status`, you will see a new change. Add that change and push a commit.

---

I'm curious what command you used to update the submodule. Is it `git submodule update --remote`?

**Comment by Fancy2209** [comment]
Pretty sure that's the one yes, I'm sorry I haven't got to this yet, been a bit busy

**Comment by CuriousTommy** [comment]
I'm going to close this PR. I created PR #1487 for updating the submodules.

**Comment by Fancy2209** [comment]
I'm sorry for never having a chance of finishing this, my bad

**Comment by CuriousTommy** [comment]
No worries! I should be thanking you exposing you to the `git submodule update --remote`.

**Pull request closed without merging**
