### PR TITLE
added shazamkit frameworks

### PR DESCRIPTION
**Pull request by vadd98**
Started importing ShazamKit frameworks. Stubs have been generated from an x64 Ventura Mac.
Still needs to fix all dependencies references.

### CODE REVIEW

**Comment by CuriousTommy** [comment]
> Adding the import line you suggested actually works, but now I'm struggling with other error references and I'm trying to fix all of them. Do you have any modus-operandi to suggest in order to speed up the referencing process?
> 
> At the moment, each time I add a reference I have to to rebuild in order to get the next missing reference.

The only files that would need manual modifications are the categories/extensions. Those files normally have a `+` in the middle. All other files should work as is ([provided that you follow the instructions from the docs](https://docs.darlinghq.org/contributing/generating-stubs.html#applying-the-stubs-to-darling)).

Also, don't forget to run `cmake .. -DREGENERATE_SDK=ON`. This command with generate symbolic links in the include and SDK folders. I don't see those symbol links in your commit.

**Comment by vadd98** [comment]
I committed the missing files. Now I'm still fixing references

**Comment by vadd98** [comment]
I'm stuck on a missing reference.
I need to import UTRefCounting but I can't find it anywhere.
This is the error I'm getting now:

> In file included from /home/vinc/Desktop/darling/src/frameworks/ShazamKit/src/UTType+SHShazamAdditions.m:20:
> /home/vinc/Desktop/darling/framework-include/ShazamKit/UTType+SHShazamAdditions.h:22:12: error: cannot find interface declaration for 'UTType'
> @interface UTType (SHShazamAdditions)
>            ^
> In file included from /home/vinc/Desktop/darling/src/frameworks/ShazamKit/src/UTType+SHShazamAdditions.m:21:
> In file included from /home/vinc/Desktop/darling/framework-include/UniformTypeIdentifiers/UniformTypeIdentifiers.h:25:
> /home/vinc/Desktop/darling/framework-include/UniformTypeIdentifiers/NSItemProvider+UTType.h:22:12: error: cannot find interface declaration for 'NSItemProvider'
> @interface NSItemProvider (UTType)
>            ^
> In file included from /home/vinc/Desktop/darling/src/frameworks/ShazamKit/src/UTType+SHShazamAdditions.m:21:
> In file included from /home/vinc/Desktop/darling/framework-include/UniformTypeIdentifiers/UniformTypeIdentifiers.h:30:
> /home/vinc/Desktop/darling/framework-include/UniformTypeIdentifiers/_UTCoreType+UTRefCounting.h:22:12: error: cannot find interface declaration for '_UTCoreType'
> @interface _UTCoreType (UTRefCounting)

Any idea?

**Comment by CuriousTommy** [comment]
In the future, I recommend using code blocks (` ``` `) instead of quote blocks (`>`) when commenting code, so that you don't accidentally ping people.

---

`UTRefCounting` is just a category name. What you need to look for is where the `_UTCoreType` class is declared in.
```objectivec
@interface ClassName ( CategoryName )
```

Looks like `_UTCoreType` lives in `UniformTypeIdentifiers/_UTCoreType.h`.

I recommend reading [Apple's documentation on Objective-C categories](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ObjectiveC/Chapters/ocCategories.html) if you want to get a better understanding on how categories works.

**Comment by vadd98** [comment]
Ah sorry about the quote block, didn't tought about that.
Anyway thanks for the support!
I fixed 2 of the missing references, but I'm still having troubles with NSItemProvider. I can see that there is a NSItemProvider.h located in framework-include/Foundation, but eventhough I try to import it with `#import <Foundation/NSItemProvider.h>` in `NSItemsProvider+UTType.h` I still get the error

**Comment by CuriousTommy** [comment]
Weird, what you did seems correct... Push what you currently have and I'll take a look at it when I have the chance.

**Comment by vadd98** [comment]
Just pushed. Thanks again for the support!
Meanwhile I'll try again to build and fix the error, in case I solve it I'll let you know

**Comment by facekapow** [comment]
Hey, just wanted to ask if you're still interested in fixing up this PR. If not, I'd be happy to fix it myself.

**Comment by vadd98** [comment]
I didn't succedded to solve the issue I had and I put everything on standby. 
If you'd like to try to fix it up you are more than welcome!

**Pull request merged**
