### PR TITLE
Add sandboxed home directory

### PR DESCRIPTION
**Pull request by kamillys**
Signed-off-by: kamil <kamillys@gmail.com>

### CODE REVIEW

**Comment by kamillys** [comment]
Resume from #185

**Comment by kamillys** [comment]
Changed copy to use "directory/." pattern.

**Comment by stek29** [comment]
`darling` is now a C program and not a shell script, isn't it?

**Comment by bugaevc** [comment]
> darling is now a C program and not a shell script, isn't it?

Yeah :smile: see #197

**Comment by stek29** [comment]
Then why won't you close this PR? :)

**Pull request closed without merging**
