### PR TITLE
Fix "Cannot determine your user name" (#715) for docker

### PR DESCRIPTION
**Pull request by danix800**
See: https://github.com/darlinghq/darling/issues/715
'getlogin' does not work inside docker when spawning shells.

### CODE REVIEW

**Comment by bugaevc** [comment]
Does not work as in returns `NULL`? or wrong data?..

**Comment by LubosD** [comment]
You're not supposed to be using the `darling` command in Docker at all. See https://github.com/darlinghq/darling-docker/blob/master/README.md

**Comment by danix800** [comment]
@bugaevc Returns `NULL` and prints `Cannot determine your user name` then exit.

**Comment by danix800** [comment]
@LubosD Sorry I could not execute mach-o directly for now inside docker. Always `Segmentation fault`, the docker image base is debian:buster (5.5.0-0.bpo.2-amd64), with darling release
[v0.1.20200331]( https://github.com/darlinghq/darling/tree/v0.1.20200331), the dkms deb is the downloaded from the release page. But `darling` from the other deb could not be executed for the same reason reported by https://github.com/darlinghq/darling/issues/715.

With this fix, based on `v0.1.20200331`, at least `darling shell` works now, and other mach-o could
be executed by or inside the shell. The dkms is installed directly inside the image, not on the host.

I saw the docker package [darling](https://github.com/darlinghq/darling/packages/187105) yesterday but I didn't know [darling-docker](https://github.com/darlinghq/darling-docker) before you referred the `README.md` for me. There is no `darling` command indeed, so how does it work? Is there any
more documents on the internals? Can the mach-o directly loaded by kernel module without `darling` command?

A few month ago I started trying to build a docker image for multi-arch cross compiling and I thought
that something like `wine` for mach-o executables would be nice to directly execute mach-o on
linux, then I met darling for the first time. Firstly I tried [utensils/docker-darling](https://github.com/utensils/docker-darling). But the darling base version [a00051b580c45b002690422819e9e2ce486f257e] therein crashes the host, possibly as reported by https://github.com/darlinghq/darling/issues/482.

By the way I also tried the latest https://github.com/darlinghq/darling/commit/1470b45ac503443aeb17f94d5751c3d2902c0a08 yesterday, but unfortunately the kernel module crashes:
```
May  9 17:03:18 danix kernel: [ 6233.987149] BUG: kernel NULL pointer dereference, address: 0000000000000078
May  9 17:03:18 danix kernel: [ 6233.987150] #PF: supervisor read access in kernel mode
May  9 17:03:18 danix kernel: [ 6233.987150] #PF: error_code(0x0000) - not-present page
May  9 17:03:18 danix kernel: [ 6233.987151] PGD 0 P4D 0 
May  9 17:03:18 danix kernel: [ 6233.987152] Oops: 0000 [#4] SMP PTI
May  9 17:03:18 danix kernel: [ 6233.987154] CPU: 4 PID: 15527 Comm: vchroot Tainted: P      D W  OE     5.5.0-0.bpo.2-amd64 #1 Debian 5.5.17-1~bpo10+1
May  9 17:03:18 danix kernel: [ 6233.987155] Hardware name: LENOVO 20QTA00DCD/20QTA00DCD, BIOS N2OET36P (1.23 ) 07/26/2019
May  9 17:03:18 danix kernel: [ 6233.987157] RIP: 0010:apparmor_bprm_committing_creds+0x2c/0x70
May  9 17:03:18 danix kernel: [ 6233.987159] Code: 44 00 00 41 54 48 63 05 62 f9 bc 00 55 65 48 8b 2c 25 c0 8b 01 00 53 48 8b 95 78 06 00 00 48 8b 7f 38 48 8b 52 78 4c 8b 24 02 <48> 8b 57 78 48 8b 1c 02 49 8b 44 24 30 48 39 43 30 74 06 f6 43 40
May  9 17:03:18 danix kernel: [ 6233.987160] RSP: 0018:ffffa4cb43f17b48 EFLAGS: 00010286
May  9 17:03:18 danix kernel: [ 6233.987160] RAX: 0000000000000000 RBX: ffffffff93d77b30 RCX: 0000000000000000
May  9 17:03:18 danix kernel: [ 6233.987161] RDX: ffff8a99bad8ee78 RSI: 0000000000000000 RDI: 0000000000000000
May  9 17:03:18 danix kernel: [ 6233.987162] RBP: ffff8a98e3fcec80 R08: ffff8a9ae73ba2f8 R09: 0000000000000001
May  9 17:03:18 danix kernel: [ 6233.987162] R10: 00000000feedfacf R11: 0000000000000004 R12: ffff8a8c474872b0
May  9 17:03:18 danix kernel: [ 6233.987163] R13: ffff8a99baf34200 R14: 0000000000000488 R15: ffff8a988b440c88
May  9 17:03:18 danix kernel: [ 6233.987164] FS:  0000000000000000(0000) GS:ffff8a9b5e500000(0000) knlGS:0000000000000000
May  9 17:03:18 danix kernel: [ 6233.987164] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
May  9 17:03:18 danix kernel: [ 6233.987165] CR2: 0000000000000078 CR3: 0000000fcecd0001 CR4: 00000000003606e0
May  9 17:03:18 danix kernel: [ 6233.987165] Call Trace:
May  9 17:03:18 danix kernel: [ 6233.987179]  security_bprm_committing_creds+0x22/0x30
May  9 17:03:18 danix kernel: [ 6233.987185]  install_exec_creds+0xe/0x70
May  9 17:03:18 danix kernel: [ 6233.987203]  setup_space+0x47/0x150 [darling_mach]
May  9 17:03:18 danix kernel: [ 6233.987216]  load64+0x716/0x8a0 [darling_mach]
May  9 17:03:18 danix kernel: [ 6233.987218]  ? vfs_read+0x11d/0x140
May  9 17:03:18 danix kernel: [ 6233.987230]  load64+0x2cc/0x8a0 [darling_mach]
May  9 17:03:18 danix kernel: [ 6233.987242]  macho_load+0x1c2/0xbe0 [darling_mach]
May  9 17:03:18 danix kernel: [ 6233.987244]  ? load_elf_binary+0xcf/0x1710
May  9 17:03:18 danix kernel: [ 6233.987245]  ? tomoyo_find_next_domain+0x2d4/0x814
May  9 17:03:18 danix kernel: [ 6233.987248]  ? load_misc_binary+0x4c/0x460 [binfmt_misc]
May  9 17:03:18 danix kernel: [ 6233.987249]  search_binary_handler+0x8a/0x1b0
May  9 17:03:18 danix kernel: [ 6233.987250]  __do_execve_file.isra.39+0x644/0x9a0
May  9 17:03:18 danix kernel: [ 6233.987252]  __x64_sys_execve+0x34/0x40
May  9 17:03:18 danix kernel: [ 6233.987255]  do_syscall_64+0x52/0x170
May  9 17:03:18 danix kernel: [ 6233.987257]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
May  9 17:03:18 danix kernel: [ 6233.987258] RIP: 0033:0x7f0b1733fe37
May  9 17:03:18 danix kernel: [ 6233.987259] Code: Bad RIP value.
```

**Comment by LubosD** [comment]
> There is no darling command indeed, so how does it work? Is there any
more documents on the internals? Can the mach-o directly loaded by kernel module without darling command?

The `darling` command only sets up a container. It is like `docker start/exec/kill`. That's why it's not needed inside Docker.

You can check the [https://github.com/darlinghq/darling-docker/blob/master/bootstrap](bootstrap) script to see the steps needed to run the first (=init) executable: launchd. The following executions (e.g. Bash when run with [https://github.com/darlinghq/darling-docker/blob/master/shell](shell)) don't need this, because they're set up automatically if they run as a child of launchd.

**Comment by danix800** [comment]
Very Nice! With `launchd` run as a daemon, I can execute any mach-o executables inside docker now! Thanks @LubosD

**Comment by danix800** [comment]
But I still think running `darling` command inside docker is convenient for testing any mach-o executables if I want to run them without exec `launchd` as pid 1.

In my container the mach-o executables are compiled on linux host through cross compiling, and I want to test them on linux container like `darling shell command` directly.

**Comment by bugaevc** [comment]
> if I want to run them without exec launchd as pid 1

We don't support that; a lot of code (in libSystem and elsewhere) assumes there's a bootstrap server.

**Comment by bugaevc** [comment]
(I mean, you can do that if you know what you're doing, but don't expect it to work for a random app.)

**Comment by CuriousTommy** [comment]
Is it fine if I close this?

**Comment by HinTak** [comment]
I think docker does not protect against https://github.com/darlinghq/darling/issues/848 , since launchd is still running on the host?

**Comment by HinTak** [comment]
And I'd be interested to know if your host's /var/tmp and /var/run (and /run) get wiped too...

**Comment by danix800** [comment]
No data is wiped for me.

I think launched is has its own MNT namespace so it shouldn't be able to touch anything on the host.

**Comment by danix800** [comment]
Maybe you could give more specific reproducing instructions for #848 so I can do some more verification. It's really scary since I've 
been running it on several hosts for about 4 months now.

**Pull request closed without merging**
