### PR TITLE
Fix OpenSSL libraries path

### PR DESCRIPTION
**Pull request by X0rg**
It refers to PR darlinghq/darling-openssl#1.
I was unable to install the darling-git package on Arch due to incorrect path for libssl098.so and libcrypto098.so.

### CODE REVIEW

**Comment by ahyattdev** [comment]
Similar fixes are needed for i386 builds, no?

**Comment by X0rg** [comment]
No: 32-bit build is installed in $PREFIX/usr/lib32, and that's right (on Arch).

**Comment by X0rg** [comment]
@ahyattdev: thanks!

**Comment by X0rg** [comment]
Also you need to merge darlinghq/darling-openssl#1 (see 51c8004). ;)

**Comment by bugaevc** [comment]
> No: 32-bit build is installed in $PREFIX/lib32, and that's right (on Arch).

Well, it's actually wrong for Fedora (and probably other RH-related distros) -- we have `lib` and `lib64` here, so it should better be conditional just like you've made it for 64.

But, as mentioned in #231, this is all temporary, so it doesn't matter much.

**Comment by bugaevc** [comment]
> Also you need to merge darlinghq/darling-openssl#1 (see 51c8004). ;)

Done

**Comment by X0rg** [comment]
Yes, sadly, the FHS on Arch is absolutely not conformant (in fact, /usr/lib64 exists, but it is a symlink on /usr/lib for compatibility, so packages should not use /usr/lib64).

**Pull request merged**
