### PR TITLE
Add open Command

### PR DESCRIPTION
**Pull request by TheBrokenRail**
This should make it easier for users to open GUI programs. Note, currently it is very basic, and does not support much functionality.

### CODE REVIEW

**Comment by bugaevc** [comment]
I'm sorry but this is not how a proper `open` would look like. First of all it'd be a part of `LaunchServices`, not its own thing (so at the very least that directory should exist, and it should be in that directory).

Then `open` should open a lot more than just app-s. See https://github.com/darlinghq/darling/issues/43 and the existing code in https://github.com/darlinghq/darling/blob/master/src/frameworks/CoreServices/LaunchServices.cpp

**Comment by TheBrokenRail** [comment]
Oh, OK.

**Comment by mritunjaymusale** [comment]
I tried to run [this](https://reactstudio.com/) using `open` but I got 
`React%20Studio.app/Contents/MacOS/React%20Studio: Failed to spawn via launchd`

**Comment by ahyattdev** [comment]
@mritunjaymusale unfortunately that's where it's stuck now. #425 tracks it

**Pull request closed without merging**
